[[Xorg_libXxf86vm]]
arch = "aarch64"
git-tree-sha1 = "4bf11146c7386ce8f56a60296a6aa34d28ddb5c4"
libc = "glibc"
os = "linux"

    [[Xorg_libXxf86vm.download]]
    sha256 = "ae184811bed4b03f26b1b85a249130635c026255a665b33ac843b73fb1ccbd3b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXxf86vm_jll.jl/releases/download/Xorg_libXxf86vm-v1.1.7+0/Xorg_libXxf86vm.v1.1.7.aarch64-linux-gnu.tar.gz"
[[Xorg_libXxf86vm]]
arch = "aarch64"
git-tree-sha1 = "b5deb95e416a498bdd1a1f2030d5991fc4b74c32"
libc = "musl"
os = "linux"

    [[Xorg_libXxf86vm.download]]
    sha256 = "8947aebcaa2544d95ea9daacc25076a23673c141970b83a03259cbfd1ba2838e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXxf86vm_jll.jl/releases/download/Xorg_libXxf86vm-v1.1.7+0/Xorg_libXxf86vm.v1.1.7.aarch64-linux-musl.tar.gz"
[[Xorg_libXxf86vm]]
arch = "aarch64"
git-tree-sha1 = "f3922a8788f69677bc183a0117c0367f31ac18e1"
os = "freebsd"

    [[Xorg_libXxf86vm.download]]
    sha256 = "6dd2a2e9165658ce9503602955068b5093189ca75ceaaafdb627deb40f294ce9"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXxf86vm_jll.jl/releases/download/Xorg_libXxf86vm-v1.1.7+0/Xorg_libXxf86vm.v1.1.7.aarch64-unknown-freebsd.tar.gz"
[[Xorg_libXxf86vm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c8b1642d9ab4ecd46532f32efc71c71e878438f8"
libc = "glibc"
os = "linux"

    [[Xorg_libXxf86vm.download]]
    sha256 = "e697640df9a1388a5108bd390f86eeee447f444256b2ec9f0914b1d6e7a18d91"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXxf86vm_jll.jl/releases/download/Xorg_libXxf86vm-v1.1.7+0/Xorg_libXxf86vm.v1.1.7.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_libXxf86vm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cb14f72f53d19159b0aa67376a4afd977be1547b"
libc = "musl"
os = "linux"

    [[Xorg_libXxf86vm.download]]
    sha256 = "d68fb1338e80e16db694c5480d5cdba4fb3c029373aca2b0df10bca7507aedb8"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXxf86vm_jll.jl/releases/download/Xorg_libXxf86vm-v1.1.7+0/Xorg_libXxf86vm.v1.1.7.armv6l-linux-musleabihf.tar.gz"
[[Xorg_libXxf86vm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "036df27556cb13387754aac972f22915ecf27c6f"
libc = "glibc"
os = "linux"

    [[Xorg_libXxf86vm.download]]
    sha256 = "9be2ea2b0bb4a69d2ef2e11e7a21ed5d88b155c09ad33deed4a1a915da4885f9"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXxf86vm_jll.jl/releases/download/Xorg_libXxf86vm-v1.1.7+0/Xorg_libXxf86vm.v1.1.7.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXxf86vm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8bca992b8abd13e40372711d0422da27f78b1cd2"
libc = "musl"
os = "linux"

    [[Xorg_libXxf86vm.download]]
    sha256 = "218a67c16a143538fdaa623c8c36795f126a43f6f45f5893e89c45642e90321b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXxf86vm_jll.jl/releases/download/Xorg_libXxf86vm-v1.1.7+0/Xorg_libXxf86vm.v1.1.7.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libXxf86vm]]
arch = "i686"
git-tree-sha1 = "8dcd4dc77c5b47ae56d41abce03db6c5a115cd0c"
libc = "glibc"
os = "linux"

    [[Xorg_libXxf86vm.download]]
    sha256 = "c197d011dc3580103b5c6b0e82914fddd30175b73a10889b435bb153bc02c3b7"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXxf86vm_jll.jl/releases/download/Xorg_libXxf86vm-v1.1.7+0/Xorg_libXxf86vm.v1.1.7.i686-linux-gnu.tar.gz"
[[Xorg_libXxf86vm]]
arch = "i686"
git-tree-sha1 = "2d84552d687b631c9fa91ae4af81a2d826f7e142"
libc = "musl"
os = "linux"

    [[Xorg_libXxf86vm.download]]
    sha256 = "3e851ed3e1ff2982e27cb384a3579fe94455d7c01cc01935e2dfd648b501a904"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXxf86vm_jll.jl/releases/download/Xorg_libXxf86vm-v1.1.7+0/Xorg_libXxf86vm.v1.1.7.i686-linux-musl.tar.gz"
[[Xorg_libXxf86vm]]
arch = "powerpc64le"
git-tree-sha1 = "b28fd2abd29d536647bcf184a74458a59d908a65"
libc = "glibc"
os = "linux"

    [[Xorg_libXxf86vm.download]]
    sha256 = "2a224847b7ffd4b97e4c611739d3058a634698cf608aea0bcf2dad6c53617640"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXxf86vm_jll.jl/releases/download/Xorg_libXxf86vm-v1.1.7+0/Xorg_libXxf86vm.v1.1.7.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libXxf86vm]]
arch = "riscv64"
git-tree-sha1 = "64661a03f0938f85f8af5a7c1a48e6dc7aab059f"
libc = "glibc"
os = "linux"

    [[Xorg_libXxf86vm.download]]
    sha256 = "495a1159013bb88b8462a5fda4385798094022f46a7e4f304c98c55b942eabb3"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXxf86vm_jll.jl/releases/download/Xorg_libXxf86vm-v1.1.7+0/Xorg_libXxf86vm.v1.1.7.riscv64-linux-gnu.tar.gz"
[[Xorg_libXxf86vm]]
arch = "x86_64"
git-tree-sha1 = "0b009804990c36c713e35df6da6a2d7ca18ac644"
libc = "glibc"
os = "linux"

    [[Xorg_libXxf86vm.download]]
    sha256 = "036ce4198bec194d4e39630d6bc5031adb6921db240394d65b6a7e63761576e1"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXxf86vm_jll.jl/releases/download/Xorg_libXxf86vm-v1.1.7+0/Xorg_libXxf86vm.v1.1.7.x86_64-linux-gnu.tar.gz"
[[Xorg_libXxf86vm]]
arch = "x86_64"
git-tree-sha1 = "ff35d9baebf231c393cb1252575c6f375f78a642"
libc = "musl"
os = "linux"

    [[Xorg_libXxf86vm.download]]
    sha256 = "d9e529a90143795b95ee6f6242208a38cb496c81a938ccaf9330b1b5dbe85bb8"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXxf86vm_jll.jl/releases/download/Xorg_libXxf86vm-v1.1.7+0/Xorg_libXxf86vm.v1.1.7.x86_64-linux-musl.tar.gz"
[[Xorg_libXxf86vm]]
arch = "x86_64"
git-tree-sha1 = "b5d53a8268c78d4d651894e7c73a9ae6b4b3287f"
os = "freebsd"

    [[Xorg_libXxf86vm.download]]
    sha256 = "8367fbd4529e5de3e1d54fb2ba6ddfd70a71ef678cdff9c6b3fb6de8812f616b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXxf86vm_jll.jl/releases/download/Xorg_libXxf86vm-v1.1.7+0/Xorg_libXxf86vm.v1.1.7.x86_64-unknown-freebsd.tar.gz"
